src/Presentation/STS/Controllers/SetLanguageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.ApiAuthorization.IdentityServer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace AspNetCoreSpa.STS.Controllers
{
    public class SetLanguageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl, string returnUrlForLanguageSwitch)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return Redirect(returnUrlForLanguageSwitch);
        }
    }
}

src/Presentation/STS/Pages/Shared/_AppScripts.cshtml
<environment include="Development">
    <script src="~/Identity/lib/jquery/dist/jquery.js"></script>
    <script src="~/Identity/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"
            asp-fallback-src="~/Identity/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery">

    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"
            asp-fallback-src="~/Identity/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"></script>

</environment>

<environment include="Development">
    <script src="~/Identity/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/Identity/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"
            asp-fallback-src="~/Identity/lib/jquery-validation/dist/jquery.validate.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.validator"
            crossorigin="anonymous"
            integrity="sha384-rZfj/ogBloos6wzLGpPkkOr/gpkBNLZ6b6yLy4o+ok+t/SAKlL5mvXLr0OXNi1Hp">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.9/jquery.validate.unobtrusive.min.js"
            asp-fallback-src="~/Identity/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive"
            crossorigin="anonymous"
            integrity="sha384-ifv0TYDWxBHzvAk2Z0n8R434FL1Rlv/Av18DXE43N/1rvHyOG4izKst0f2iSLdds">
    </script>
</environment>

<script src="~/Identity/js/site.js" asp-append-version="true"></script>

src/Presentation/STS/Pages/Shared/_AppStyles.cshtml
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" />

<environment include="Development">
    <link rel="stylesheet" href="~/Identity/lib/bootstrap/dist/css/bootstrap.css" />
</environment>
<environment exclude="Development">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</environment>

<link rel="stylesheet" href="~/Identity/css/site.css" asp-append-version="true" />

src/Presentation/STS/Pages/Shared/_Footer.cshtml
<footer class="footer border-top text-muted">
    <div class="container">
        &copy; 2020 - AspNetCoreSTS - <a asp-area="" asp-page="Privacy">Privacy</a>
    </div>
</footer>

src/Presentation/STS/Pages/Shared/_Header.cshtml
@using Microsoft.AspNetCore.Mvc.ViewEngines
@inject ICompositeViewEngine Engine

@{
    //https://stackoverflow.com/a/18853875/1190512
    string returnUrl = ViewData.Eval("ReturnUrl").ToString();
    string appTitle = ViewData.Eval("AppTitle").ToString();
}
<header>
    <nav class="navbar navbar-expand-sm navbar-light navbar-toggleable-sm bg-white border-bottom box-shadow mb-3">
        <img class="header-image-img"
             src="~/icon.png"
             alt="STS" />
        <a class="nav-link text-dark" href="@returnUrl" title="Return to @appTitle">
            <i class="fas fa-home"></i>
            @appTitle
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            @{
                var result = Engine.FindView(ViewContext, "_LoginPartial", isMainPage: false);
            }
            @if (result.Success)
            {
                await Html.RenderPartialAsync("_LoginPartial", returnUrl);
            }
            else
            {
                throw new InvalidOperationException("The default Identity UI layout requires a partial view '_LoginPartial' " +
                                                    "usually located at '/Pages/_LoginPartial' or at '/Views/Shared/_LoginPartial' to work. Based on your configuration " +
                                                    $"we have looked at it in the following locations: {System.Environment.NewLine}{string.Join(System.Environment.NewLine, result.SearchedLocations)}.");
            }

            <partial name="_SelectLanguagePartial"/>

        </div>
        
    </nav>
</header>

src/Presentation/STS/Pages/Shared/_Layout.cshtml
@using AspNetCoreSpa.Application.Abstractions
@using Microsoft.Extensions.Localization
@inject IDeploymentEnvironment DeploymentEnvironment
@inject IClientInfoService ClientInfoService
@inject IStringLocalizer<string> StringLocalizer

@{
    var client = ClientInfoService.GetClient();
    var appTitle = StringLocalizer.GetString("app_title");
    var returnLink = client.ClientUri ?? "/";
    var pageTitle = ViewData["Title"]?.ToString();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <link rel="shortcut icon" type="image/png" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui">

    <title>
        <if hide="string.IsNullOrEmpty(appTitle)">
            @appTitle <if hide="string.IsNullOrEmpty(pageTitle)">- @pageTitle</if>
        </if>
    </title>

    <partial name="_AppStyles" />

</head>
<body>

    @await Html.PartialAsync("_Header", new { ReturnUrl = returnLink, AppTitle = appTitle })

    <div class="container">
        <partial name="_CookieConsentPartial" optional />

        <main role="main">
            <if hide="string.IsNullOrEmpty(pageTitle)">
                <div class="row">
                    <div class="col">
                        <h1>
                            @pageTitle
                        </h1>
                    </div>
                </div>
            </if>
            @RenderBody()
        </main>
    </div>

    <partial name="_Footer" />

    <partial name="_AppScripts" />

    @RenderSection("Scripts", required: false)

<cache>
    <!-- OS: @DeploymentEnvironment.OS -->
    <!-- Machine: @DeploymentEnvironment.MachineName -->
    <!-- Framework: @DeploymentEnvironment.RuntimeFramework -->
    <!-- Environment: @DeploymentEnvironment.EnvironmentName -->
    <!-- Branch: @DeploymentEnvironment.Branch -->
    <!-- Tag: @DeploymentEnvironment.Tag -->
    <!-- CommitSha: @DeploymentEnvironment.CommitSha -->
</cache>

</body>
</html>

src/Presentation/STS/Pages/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
        .ToList();
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    @{
        var location = new Uri($"{Context.Request.Scheme}://{Context.Request.Host}{Context.Request.Path}{Context.Request.QueryString}");

        var url = location.AbsoluteUri;
        var returnUrlForLanguageSwitch = Context.Request.Path;

        if (Context.Request.QueryString.HasValue)
        {
            returnUrlForLanguageSwitch = $"{Context.Request.Path}{Context.Request.QueryString.Value}";
        }
    }
    <form class="form-inline" id="selectLanguage" asp-controller="SetLanguage" asp-action="SetLanguage" asp-route-returnUrl="@returnUrlForLanguageSwitch" method="post" role="form">
        <label class="form-label paddingright5px">Language:&nbsp;</label>
        <div class="input-group">
            <select class="custom-select" name="culture" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
            <input type="hidden" name="returnUrlForLanguageSwitch" id="returnUrlForLanguageSwitch" value="@url" />
            <div class="input-group-append">
                <button type="submit" class="btn btn-outline-secondary">Save</button>
            </div>
        </div>
    </form>
</div>